// <auto-generated />
using GotGame.RestServer.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GotGame.RestServer.Migrations
{
    [DbContext(typeof(GoTGameContextDb))]
    [Migration("20190504184853_GameRulesModelUpdate")]
    partial class GameRulesModelUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GotGame.RestServer.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("Name");

                    b.Property<string>("PasswordHash");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GotGame.RestServer.Models.GameRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllHouses");

                    b.Property<bool>("CanLookPlayerCard");

                    b.Property<int>("GameId");

                    b.Property<bool>("LargeCastleDefence");

                    b.Property<int>("MaxPlayers");

                    b.Property<bool>("MercaneryAvaible");

                    b.Property<bool>("RandomHouses");

                    b.Property<int>("RoundsCount");

                    b.Property<bool>("SmallCastleDefence");

                    b.Property<int>("WinCastlesCount");

                    b.Property<string>("WinCondition")
                        .IsRequired();

                    b.Property<int>("WinPointsCount");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameRules");
                });

            modelBuilder.Entity("GotGame.RestServer.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId");

                    b.Property<string>("House");

                    b.Property<string>("IpAddress");

                    b.Property<bool>("IsGameCreator");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GotGame.RestServer.Models.GameRules", b =>
                {
                    b.HasOne("GotGame.RestServer.Models.Game")
                        .WithOne("GameRules")
                        .HasForeignKey("GotGame.RestServer.Models.GameRules", "GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GotGame.RestServer.Models.Player", b =>
                {
                    b.HasOne("GotGame.RestServer.Models.Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
